#Managing iptables
# Open TCP port 80 HTTP
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
# Open TCP port 22 SSH
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 22
    jump: ACCEPT
# Open TCP port 2812 MONIT
- iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 2812
    jump: ACCEPT

- iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
- iptables:
    chain: FORWARD
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
- iptables:
    chain: OUTPUT
    policy: ACCEPT

- name: save rules
  command: iptables-save